name: Generate static page
on:
  workflow_dispatch:
  push:
    branches:
      - main  
    paths:
      - 'README.md'
env:
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com
  
jobs:
  generate_website:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v7
      
      - name: Create branch
        run: |
          git checkout -b static-website-update

      - uses: davorg/readme-to-index@v1
        with:
          readme: README.md
          output: docs/index.html
          css_url: https://cdn.jsdelivr.net/gh/kimeiga/bahunya/dist/bahunya.min.css
          
      - name: Commit & send PR
        # if: env.exit != 'true'
        run: |
          export GITHUB_TOKEN=${{ github.token }}
          git config --global user.name "$USERNAME"
          git config --global user.email "$USERNAME@$ADDRESS_SUFFIX"
          git add --all docs
          git commit -m "Updated docs/index.html"
          git push origin static-website-update
          gh pr create --title "Update static website" --body "Updated from README.md"
